# Generated by Django 4.2.21 on 2025-05-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('director', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('film_file', models.FileField(upload_to='films/')),
            ],
        ),
    ]
